"""normalize telemetry

Revision ID: 3bb7f768ab78
Revises: 53e517859599
Create Date: 2026-06-27 16:29:49.637841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bb7f768ab78'
down_revision: Union[str, Sequence[str], None] = '53e517859599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('rule', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('process', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('remote_ip', sa.String(length=64), nullable=True),
    sa.Column('remote_port', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telemetry_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('process', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('local_ip', sa.String(length=64), nullable=False),
    sa.Column('local_port', sa.Integer(), nullable=False),
    sa.Column('remote_ip', sa.String(length=64), nullable=True),
    sa.Column('remote_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telemetry_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telemetry_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('telemetry_sessions', 'system_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_sessions', sa.Column('system_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('process_events')
    op.drop_table('network_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
